### ISSUE TITLE
Latest versions with security updates missing at Snap store

### ISSUE THREAD

**Issue by CvH** [RocketChat/rocketchat-server-snap#49]
- 5.0.7 (5.0.6 latest at store) is missing at the Sap store since (today) 23 days
- 4.8.6 (4.8.3 latest at store) is missing at the Sap store, no updates for 2 months

would be nice if the updates get automated, that is ! still ! a repeating problem since years

**Comment by CvH** [comment]
still the same problem today :( 
@debdutdeb any news on that ?

**Comment by CvH** [comment]
looks like it works again, no idea if manually triggered or really working this time :)

**Comment by CvH** [comment]
and ofc it is not working again
snapstore was not updated, din't got 6.0.1 or 6.1.0

**Comment by CvH** [comment]
I know I'm talking to myself here but are there any chance to get an update to a recent version at the snapstore @debdutdeb ?
The release process seams still completely broken for snaps and docker :(
No updates, no bugfixes, no security updates while they are available at the git.

If this is a internal problem that can't be fixed could you guide us to a installation method that is actively supported so we could get at least bugfixes and security fixes?

**Comment by debdutdeb** [comment]
Hey @CvH there was an issue with the workflow, and the tests. If you look at the commits yesterday night I made some changes to it. Two more things need to be done before I can publish on snap today - 1) a migration for an internal change, 2) fixing the affected test. 

Additionally, I had to hold off one release because of an apps engine bug that could potentially "break" the system if you just trigger a setting change.

**Comment by CvH** [comment]
@debdutdeb tx for looking into this, that sounds promising

currently its a tough task to update rocketchat because you never know if you get stranded on one version with all bugs/problems without a chance to get a bugfix for the next 2-3 months

**Comment by CvH** [comment]
tx
